# Numpy -1 

While lists provide general functionality for handling arbitrary data collections, when it comes to vecor/matrix operations on numeric arrays, like elementwise addition or multiplication for example, general lists are not that useful (as in general lists do not have to be numeric, there is no reason for them to have this specific numeric funcionality; list summation is perhaps one of the rare exceptions). 

Furtunately there is a module numpy that bridges this gap. It provides a new data type - numpy array, being a single or multi-dimensional vector where all the elements are of the same type, say numeric. Numpy arrays inherit most of the funcionality from a generic list and implement a broad range of additional vector and matrix operations for it.

In [1]:
import numpy as np #in order to use numpy we need to import the module; can create a short acronym for it

In [2]:
#a simplest way of creating a numpy array is converting a list to it
a=np.array(range(10))

In [3]:
a #it looks similar to a list but now it shows up as an array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#arithmetic operations with are now by default elementwise
a+1 #if we add one to an array we add it to all the elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a*2 #if we multiply, we mupliplty all the elements

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
a**2 #or this way we can create an array of squares of the values from our list

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
#we can also add arrays element-wise like
a**2+a

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

Consider an example of an array of air temperature readings

In [8]:
#temperatures in Forenheit
T=np.array([65,66,68,66,64,63,69,84,66,70,72,63,65,70,69,65,83], dtype=float)
#if we want to make sure those elements are treated as floating point numbers rather than interegers
#we may want to explicitly specify the element type 

Now lets convert those temperature readings from Forenhiet to Celsius using a simple element-wise operation, just like we'd do for a single number

In [10]:
(T-32)/1.8 #subtract 32F coresponding to 0C and divide by 1.8; but as we apply it to an entire array we get an array as a result

array([18.33333333, 18.88888889, 20.        , 18.88888889, 17.77777778,
       17.22222222, 20.55555556, 28.88888889, 18.88888889, 21.11111111,
       22.22222222, 17.22222222, 18.33333333, 21.11111111, 20.55555556,
       18.33333333, 28.33333333])

In [11]:
#also there is a number of built-in methods returning various properties of arrays

In [12]:
#like mean
T.mean()

68.70588235294117

In [13]:
#or standard deviation
T.std()

5.958332829223811

In [14]:
#And if I want to find the ubnormally high tempetarues say those above 80F; I can create a boolean index of those
ind=T>80; ind
#being an numpy array of boolean values 

array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False,  True])

In [15]:
#count the number of true instances corresponding to the outliers
sum(ind)

2

In [16]:
#or find those outlier values by ising an array ind to index an original array A
T[ind]

array([84., 83.])

In [17]:
T[T>80] #we can also write it in one line

array([84., 83.])